### ISSUE TITLE
больше пространства между название - прямоугольник - футер

### ISSUE THREAD

**Issue by skasatkin** [dotcdev/webforms#1]
прямоугольник нужно слегка сузить
размер зафиксировать, исключив прыжки при добавлении вопросов/переходе на другую секцию

дать блоку дыхание сверху и снизу, избавиться от пустых мест сверху-снизу, согласно изображению 

![Frame 1](https://user-images.githubusercontent.com/33102793/185765312-6b089b15-266a-4ca4-a110-090630049b39.png)

**Comment by stepanik537** [comment]
внутри блока пусть будет слайдер, желательно кастомный, какой отражен в фигме на первой секции

**Comment by extpankov** [comment]
`.form__content { max-height: 600px }` - прямоугольник остается 600px, если даже содержимое больше  
делать отступы сверху и снизу не вижу смысла. если он есть, реопен. 
добавил стандартный скролл. кастомный - отдельная задача. 
fixed.

**Comment by extpankov** [comment]
ready for tests

**Comment by skasatkin** [comment]
min-height: 600px

**Comment by extpankov** [comment]
new task - https://github.com/dotcdev/webforms/issues/13
closed
