### ISSUE TITLE
комбо должно выделяться на фоне основного блока, иметь название. в случае с реализуемой формой название секции "Команда", название комбо "Список участников" (figma)

### ISSUE THREAD

**Issue by extpankov** [dotcdev/webforms#11]

**Comment by extpankov** [comment]
а чем щас то комбо не выделяется?) тень из фигмы добавил, цвет фона у тебя тот же.
название прикручу, в работе.

**Comment by skasatkin** [comment]
а, реально выделяется
не буду напоминать, кто все возможные элементы управления зафигарил в само комбо и меня дезориентировал

**Comment by extpankov** [comment]
иди в трещину, я вообще работаю за бесплатно

**Comment by extpankov** [comment]
добавлено название комбо `.combo__name`

fixed

**Comment by extpankov** [comment]
ready for tests
