### ISSUE TITLE
пропиши мне названия блоков всех готовых типов вопросов

### ISSUE THREAD

**Issue by skasatkin** [dotcdev/webforms#12]
types of questions
1. short input => 
2. long input => 
3. dropdown => 
4. markdown => 
5. expandable markdown => 
6. checkmark => 

чтобы я имел возможность сделать бэк вывод корректно

**Comment by extpankov** [comment]
классами?
типа
short input => .question__field_short-ans

**Comment by skasatkin** [comment]
видимо да

**Comment by extpankov** [comment]
short input => .question__field_short-ans
long input => not used on this proj ( .question__field_large-ans)
dropdown => .question__field_dropdown
markdown => not realized
expandable markdown => not realized
checkmark => .checkmark
