### ISSUE TITLE
отступы (figma)

### ISSUE THREAD

**Issue by skasatkin** [dotcdev/webforms#13]
делать отступы сверху и снизу не вижу смысла. если он есть, реопен. 

_Originally posted by @extpankov in https://github.com/dotcdev/webforms/issues/1#issuecomment-1221526916_

**Comment by skasatkin** [comment]
> прямоугольник нужно слегка сузить размер зафиксировать, исключив прыжки при добавлении вопросов/переходе на другую секцию
> 
> дать блоку дыхание сверху и снизу, избавиться от пустых мест сверху-снизу, согласно изображению
> 
> ![Frame 1](https://user-images.githubusercontent.com/33102793/185765312-6b089b15-266a-4ca4-a110-090630049b39.png)

**Comment by skasatkin** [comment]
смысл в том, что такой дизайн-макет
прикреплю вскоре фигму

**Comment by extpankov** [comment]
![Image](https://user-images.githubusercontent.com/89220319/185790520-9e099366-248e-4f28-8d9f-f8d60aecda28.png)

примерно так? (на отступы забей, просто для примера строчку кода переписал)
а пустое место куда

**Comment by skasatkin** [comment]
от верхнего края еще отступи какое-то количество, равняясь на мой скрин 
и между названием - самой формой должно быть чуть больше место (на случай, если туда когда-нибудь хренакнем описание) 

а футер, получается, максимально близко к низу пусть будет, тоже с небольшим отсутпом

**Comment by extpankov** [comment]
`.form { margin-top: 100px; }`
'.form__content { display: flex; align-items: center }
`.section { width: 100% }`

but there is the kolkhoz style, isn't it? @skasatkin 
![Снимок экрана 2022-08-21 в 21 55 52](https://user-images.githubusercontent.com/89220319/185806615-303588f6-013f-4dd0-80a2-f361d62708ac.png)

**Comment by skasatkin** [comment]
ой а я совсем не обратил внимание

информация о команде - конечно же сверху по центру (небольшой отступ от начала блока) 
вопросы после равного предыдущему отступа пойдут

кнопка далее должна иметь отступ от нижнего края такой же, какой имеет от правого

**Comment by skasatkin** [comment]
то есть, когда вопросов мало, снизу будет пустовато = норма

**Comment by extpankov** [comment]
![Image](https://user-images.githubusercontent.com/89220319/185807480-1a092f4b-33d8-4d11-9478-39580633ef72.png)

what about this?

**Comment by skasatkin** [comment]
little bit хорошо 
типа Гугл

**Comment by extpankov** [comment]
ready for tests
