### ISSUE TITLE
секция "Капитан"

### ISSUE THREAD

**Issue by extpankov** [dotcdev/webforms#14]

**Comment by extpankov** [comment]
<img width="577" alt="Снимок экрана 2022-08-21 в 15 07 07" src="https://user-images.githubusercontent.com/89220319/185790125-443ab6d8-b9a5-4e2b-8b9a-7abd0dfc0c27.png">

**Comment by skasatkin** [comment]
ОБЯЗ Короткий текстовый (ФИО) Фамилия Имя Отчество
ОБЯЗ Короткий текстовый (Телефон) Номер для связи 
ОБЯЗ Короткий текстовый (regex) Ссылка на страницу ВКонтакте
Кнопка Отправить

**Comment by extpankov** [comment]
вставка новой секции перед "участниками"

**Comment by extpankov** [comment]
ready for tests
