### ISSUE TITLE
новый футер

### ISSUE THREAD

**Issue by skasatkin** [dotcdev/webforms#2]
![Frame 2](https://user-images.githubusercontent.com/33102793/185765377-54b02ff9-2c12-4da7-805f-9baf3172e44e.png)

политика и сообщение об ошибке - две разные ссылки, пока просто пусть ведут на /

**Comment by extpankov** [comment]
in work

**Comment by extpankov** [comment]
в следующий раз прикладывай .fig

**Comment by extpankov** [comment]
ready

**Comment by extpankov** [comment]
ready for tests
