### ISSUE TITLE
main page > pseudo notification (Figma)

### ISSUE THREAD

**Issue by skasatkin** [dotcdev/webforms#23]
for draw errors 

--
iCloud Notes

**Comment by extpankov** [comment]
что по анимациям?

**Comment by skasatkin** [comment]
пока отделаемся простым fade-in, потом должно мигнуть заметно 

исчезать не должно

**Comment by skasatkin** [comment]
если текста становится больше, чем минимальный установленный размер - растет вширь влево до размера, не более, чем две минимальных ширины, дальше продолжает расти вниз, но не более, чем 1.5 минимальной высоты

**Comment by extpankov** [comment]
> потом должно мигнуть заметно

??

**Comment by extpankov** [comment]
> если текста становится больше, чем минимальный установленный размер - растет вширь влево до размера, не более, чем две минимальных ширины
.notify__content { min-width: 308px; max-width: calc(2 * 308px); }

> дальше продолжает расти вниз, но не более, чем 1.5 минимальной высоты
.notify__content { max-height: calc(1.5 * 65px); }

![Снимок экрана 2022-08-23 в 16 57 43](https://user-images.githubusercontent.com/89220319/186177476-dc167505-d9b1-409f-8074-44350cf51aec.png)
отрабатывает вполне естественно

**Comment by extpankov** [comment]
> если текста становится больше, чем минимальный установленный размер - растет вширь влево до размера, не более, чем две минимальных ширины

`.notify__content { min-width: 308px; max-width: calc(2 * 308px); }`

> дальше продолжает расти вниз, но не более, чем 1.5 минимальной высоты

`.notify__content { max-height: calc(1.5 * 65px); }`


![Снимок экрана 2022-08-23 в 16 57 43](https://user-images.githubusercontent.com/89220319/186177476-dc167505-d9b1-409f-8074-44350cf51aec.png) 

отрабатывает вполне естественно

**Comment by extpankov** [comment]
сразу же настроил отображение нескольких уведомлений сразу
мигание -- отдельный таск. не понимаю как реализацию ты хочешь видеть
ready for test, closed.

**Comment by skasatkin** [comment]
![image](https://user-images.githubusercontent.com/33102793/186513796-bb795bfd-5a36-4f5f-80f1-114358bdad76.png)

цвет текста не соответствует ожиданиям, заданный: #D2D1D1
размер выше заданного
симметричный отступ 50x50 от верхнегоXправого краев не соблюден 

текст не должен быть центрирован, он должен иметь оступ от левого края блока в 1.7 раза больше, чем отступ кружочка от правого края

**Comment by extpankov** [comment]
прикола отдельного цвета в уведомлениях я не понял

размер восстановил, багнулся когда адаптировал для нескольких уведомлений сразу. отступ тоже должен был пофикситься, мне лень, сам считай. 

круг вернул. тварь-браузер сжирал из-за жадного флекс контейнера. 

откуда ты взял цифру 1.7 вопрос очень щепетильный, хуй с тобой
`.notify__name { margin-left: calc(1.7 * 10px); }`
и только попробуй доебаться что там не 17 пикселей

закрыто

**Comment by extpankov** [comment]
прАшу прАщения

наглый браузер украл ещё двадцать пикселей из-за внутреннего отступа. вернул двадцать пикселей с барской казны специально для контейнера уведомлений. 
теперь точно закрыто
