### ISSUE TITLE
forms mobile (Figma)

### ISSUE THREAD

**Issue by skasatkin** [dotcdev/webforms#24]
![Image](https://user-images.githubusercontent.com/33102793/186140107-13a3d22e-24ae-446d-8288-cb0988b397a9.png)

**Comment by extpankov** [comment]
разобью на отдельные задачи

**Comment by extpankov** [comment]
![Image](https://user-images.githubusercontent.com/89220319/186182075-dc37fbbd-ecb2-445d-8cac-5df6172858de.png)

лучший макет, только по таким и работаю.

**Comment by skasatkin** [comment]
так ведь все предельно ясно
и не так давно, дорогой друг, вы выражали яркость своего энтузиазма
творите, пользуйтесь им, сочиняйте!

**Comment by extpankov** [comment]
яркость энтузиазма не заключается в исполнении обязанностей веб-дизайнера)

**Comment by extpankov** [comment]
- [ ] diplaying .question__field_dropdown
- [ ] button "удалить участника"
- [ ] очень маленькие мобилы (width 320px)

**Comment by extpankov** [comment]
@skasatkin куда кнопку девать? вверх вниз?

![Снимок экрана 2022-08-24 в 10 46 44](https://user-images.githubusercontent.com/89220319/186361239-7f04461b-8627-4a03-af08-710d69c47037.png)

**Comment by extpankov** [comment]
![Снимок экрана 2022-08-24 в 10 47 47](https://user-images.githubusercontent.com/89220319/186361435-5bf6ff4c-10bd-4d8e-a582-cd71d502942b.png)

:(((((((((((((

**Comment by extpankov** [comment]
залил изменения
на 11 айфоне все красиво
вопрос по кнопке "удалить участника" открыт

**Comment by skasatkin** [comment]
вниз

**Comment by skasatkin** [comment]
крепани в телеги лонг-скриншоты из сафари с физического телефона

**Comment by extpankov** [comment]
![image](https://user-images.githubusercontent.com/89220319/186658399-97e52853-f11e-47e0-a429-c957ff1f216b.png)
