### ISSUE TITLE
pseudo notificaition

### ISSUE THREAD

**Issue by skasatkin** [dotcdev/webforms#25]
![image](https://user-images.githubusercontent.com/33102793/186514574-ca7e0fb1-aaba-45b2-8659-2d06058022c6.png)

**Comment by extpankov** [comment]
конкретнее, че сделать надо

**Comment by skasatkin** [comment]
прикрепляю слова нашего эксперта по качеству реализации программного обеспечения и адаптивных дизайнов
![image](https://user-images.githubusercontent.com/33102793/186525747-14c65ebf-2a6e-4f5b-bd4f-326f0f51c749.png)

и вместе с этими приколами ссылаюсь на слова из схожего вопроса, тк оно здесь надо упомянуть
> текст не должен быть центрирован, он должен иметь оступ от левого края блока в 1.7 раза больше, чем отступ кружочка от правого края #23

**Comment by extpankov** [comment]
эксперта по качеству реализации программного обеспечения и адаптивных дизайнов в ~~ахуе~~ недоумении. он считает, что таска полностью копирует #23. если это не так - реопен. 

закрыто
