### ISSUE TITLE
кнопка очистки формы

### ISSUE THREAD

**Issue by skasatkin** [dotcdev/webforms#3]
пусть наследует стили других кнопок, но цвет - свой
кнопка 252728
текст FFFFFF

![Frame 2](https://user-images.githubusercontent.com/33102793/185765377-54b02ff9-2c12-4da7-805f-9baf3172e44e.png)

**Comment by extpankov** [comment]
не забывай про .fig

ready

**Comment by extpankov** [comment]
ready for tests
