### ISSUE TITLE
кнопка в виде ссылки "убрать участника" в комбо

### ISSUE THREAD

**Issue by extpankov** [dotcdev/webforms#4]

**Comment by extpankov** [comment]
добавлено

**Comment by extpankov** [comment]
ready for tests

**Comment by skasatkin** [comment]
**!!!** "кнопка в виде ссылки"
напротив каждого участника
положение - правый верхний угол

**Comment by extpankov** [comment]
кнопка в виде ссылки в моем понимании: 

![Image](https://user-images.githubusercontent.com/89220319/185806864-a3aa476e-6883-4843-8f47-131c91597c71.png)

`{
display: flex;
align-items: center;
margin-right: 25px;
color: blue;
text-decoration: underline;
position: absolute;
top: 655px;
}`

**Comment by skasatkin** [comment]
оно

крепи туда стиль аналогичный .section__name и и цвет, как на кнопке добавить участника

**Comment by extpankov** [comment]
визуальная часть реализована в последнем коммите
функциональная - завтра

**Comment by extpankov** [comment]
функционал в здравом смысле лежит на бекендере
closed
