### ISSUE TITLE
вертикальный слайдер в секциях, где кол-во блоков не будет вмещаться в силу ограниченности размера блока (issue#1)

### ISSUE THREAD

**Issue by extpankov** [dotcdev/webforms#5]

**Comment by extpankov** [comment]
in work

**Comment by extpankov** [comment]
in work

**Comment by extpankov** [comment]
fixed

**Comment by extpankov** [comment]
ready for tests

**Comment by skasatkin** [comment]
не оно

название секции должно всегда находиться в одной точке, независимо от положения скролла
кнопки назад и отправить тоже

если переполнено комбо - скролл должен быть в комбо
если переполнена секция - тогда скролл в секции

**Comment by extpankov** [comment]
очень сложно в представлении
либо фигму, либо запиши видео и объясни

**Comment by skasatkin** [comment]
откладываем пока
возможно, не имеет смысла 
либо другой способ (статифицировать название секции и кнопки действия)
