### ISSUE TITLE
сделать больше горизонтальные отступы для текста на кнопках

### ISSUE THREAD

**Issue by extpankov** [dotcdev/webforms#6]
"добавить участника прям совсем слиплось"

**Comment by extpankov** [comment]
требует корректировки
@skasatkin 


![Image](https://user-images.githubusercontent.com/89220319/185784964-34b51aa4-edb6-44c2-a454-bdb1fb2be879.png)
вот тут?

**Comment by skasatkin** [comment]
+

**Comment by extpankov** [comment]
in work

**Comment by extpankov** [comment]
.button__combo  { padding: 0 20px; }

![Image](https://user-images.githubusercontent.com/89220319/185785460-c9223154-2222-4821-af73-de37c77bb15d.png)

**Comment by extpankov** [comment]
fixed

**Comment by extpankov** [comment]
ready for tests
