### ISSUE TITLE
кнопки на второй секции, как и на первой, должны иметь одинаковый отступ от правого нижнего угла

### ISSUE THREAD

**Issue by extpankov** [dotcdev/webforms#9]

**Comment by extpankov** [comment]
@skasatkin 
конкретнее со скринами

**Comment by skasatkin** [comment]
![image](https://user-images.githubusercontent.com/33102793/185787586-43b3c67d-9929-4cb6-829e-68f658e7ff8e.png)

**Comment by skasatkin** [comment]
> @skasatkin конкретнее со скринами

![image](https://user-images.githubusercontent.com/33102793/185787597-c52b3f48-ded7-48ef-958a-7fbde7e07d65.png)

**Comment by extpankov** [comment]
`.section {
padding: 20px;
}`
должно быть всё ровно

**Comment by skasatkin** [comment]
> `.section { padding: 20px; }` должно быть всё ровно

look at this
![image](https://user-images.githubusercontent.com/33102793/185787845-1919ac5d-c5b3-4c1f-9975-2853da67dac9.png)

**Comment by extpankov** [comment]
стоило уточнить, что речь про комбо. 
`.combo__wrapper { padding: 50px 20px 20px 20px; }`

ready

**Comment by extpankov** [comment]
кнопки вынесены из комбо

fixed

**Comment by extpankov** [comment]
кнопки вынесены за комбо (баг)

(re)fixed

**Comment by extpankov** [comment]
ready for tests
